apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-b10902063-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgadmin-b10902063
  template:
    metadata:
      labels:
        app: pgadmin-b10902063
    spec:
      containers:
      - name: pgadmin-b10902063
        image: dpage/pgadmin4
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: b10902063@nasa.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin
 
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-b10902063-svc
spec:
  selector:
    app: pgadmin-b10902063
  ports:
  - port: 80
  type: ClusterIP